# Estamos em Produção

### Verificar o como as escala das falhas ficam classificadas utilizando o modelo de árvore decisão.

#### 1 - Carregar o modelo treinado
#### 2 - Carregar os dados a serem inferidos
#### 3 - Fazer as inferências
#### 4 - FIM

In [1]:
# Carregando modelo

import pickle
model = pickle.load(open('model_DT.sav', 'rb'))

In [2]:
import pandas as pd

df = pd.read_excel('O_G_Equipment_Data.xlsx')
df.head(2)

,Cycle,Preset_1,Preset_2,Temperature,Pressure,VibrationX,VibrationY,VibrationZ,Frequency,Fail
0,1,3,6,44.235186,47.657254,46.441769,64.820327,66.454520,44.483250,False
1,2,2,4,60.807234,63.172076,62.005951,80.714431,81.246405,60.228715,False

In [4]:
df = pd.get_dummies(df, columns = ['Preset_1', 'Preset_2'])
df.head(2)

,Cycle,Temperature,Pressure,VibrationX,VibrationY,VibrationZ,Frequency,Fail,Preset_1_1,Preset_1_2,Preset_1_3,Preset_2_1,Preset_2_2,Preset_2_3,Preset_2_4,Preset_2_5,Preset_2_6,Preset_2_7,Preset_2_8
0,1,44.235186,47.657254,46.441769,64.820327,66.454520,44.483250,False,0,0,1,0,0,0,0,0,1,0,0
1,2,60.807234,63.172076,62.005951,80.714431,81.246405,60.228715,False,0,1,0,0,0,0,1,0,0,0,0

In [5]:
# Removendo as colunas para realizar a predição 
df = df.drop(columns={'Fail'})
df.head(2)

,Cycle,Temperature,Pressure,VibrationX,VibrationY,VibrationZ,Frequency,Preset_1_1,Preset_1_2,Preset_1_3,Preset_2_1,Preset_2_2,Preset_2_3,Preset_2_4,Preset_2_5,Preset_2_6,Preset_2_7,Preset_2_8
0,1,44.235186,47.657254,46.441769,64.820327,66.454520,44.483250,0,0,1,0,0,0,0,0,1,0,0
1,2,60.807234,63.172076,62.005951,80.714431,81.246405,60.228715,0,1,0,0,0,0,1,0,0,0,0

In [6]:
# Inferência

inferences = model.predict(df)
df['Resultado'] = inferences
df.head(4)

,Cycle,Temperature,Pressure,VibrationX,VibrationY,VibrationZ,Frequency,Preset_1_1,Preset_1_2,Preset_1_3,Preset_2_1,Preset_2_2,Preset_2_3,Preset_2_4,Preset_2_5,Preset_2_6,Preset_2_7,Preset_2_8,Resultado
0,1,44.235186,47.657254,46.441769,64.820327,66.454520,44.483250,0,0,1,0,0,0,0,0,1,0,0,False
1,2,60.807234,63.172076,62.005951,80.714431,81.246405,60.228715,0,1,0,0,0,0,1,0,0,0,0,False
2,3,79.027536,83.032190,82.642110,98.254386,98.785196,80.993479,0,1,0,1,0,0,0,0,0,0,0,False
3,4,79.716242,100.508634,122.362321,121.363429,118.652538,80.315567,0,1,0,0,0,1,0,0,0,0,0,False

In [7]:
df_t = pd.DataFrame(df.Resultado.value_counts().sort_index())
df_t = df_t.reset_index()
df_t = df_t.rename({'index': 'Fail_Category'}, axis=1)
df_t

   Fail_Category  Resultado
0          False        737
1           True         63